### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Motzee** [Motzee/jeanvoitdupate-back#1]
- [x] Création projet symfony
- [x] Mise en place FosUserBundle
- [x] 3 statuts ; admin, preparateur et client
- [x] membre de test pour chaque statut
- [x] diagramme de classes
- [x] Création Entités : Product
- [x] Création Entités : Basket
- [x] Création Entités : Choicebasket
- [x] Création Entités : Address
- [x] Modification Entités User
- [x] Création Entités : Order
- [ ] Création Entités : Slide
- [x] Jointures de tables
- [x] Basculement dans bases de données des entités
- [ ] Jointures : nullable et cascades (et rectification BDD)
- [ ] API : réfléchir sur des CRUD à avoir disponibles
- [ ] personnaliser formulaires fos_user, 
- [ ] restriction des accès
